version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - barbary_static_volume:/barbary/static
      - barbary_files_volume:/barbary/files
    networks:
      - nginx_network

volumes:
  barbary_static_volume:
    external: true
  barbary_files_volume:
    external: true
networks:
  nginx_network:
    external: true
