# Generated by Django 2.2 on 2022-02-27 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='images')),
                ('alt_thumbnail', models.CharField(blank=True, max_length=128, null=True)),
                ('title_thumbnail', models.CharField(blank=True, max_length=128, null=True)),
                ('keywords', models.CharField(blank=True, max_length=256, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('p', 'publish'), ('d', 'draft')], max_length=1)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
    ]
