# Generated by Django 2.2 on 2022-08-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220227_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
